import = ["/home/jens/.config/alacritty/alacritty-theme/themes/horizon-dark.yaml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0xababab"
blue = "0xa6aaf1"
cyan = "0x7ad5ff"
green = "0x57e690"
magenta = "0xe07de0"
red = "0xdc7974"
white = "0xfeffff"
yellow = "0xece100"

[colors.normal]
black = "0xababab"
blue = "0xa6aaf1"
cyan = "0x7ad5ff"
green = "0x57e690"
magenta = "0xe07de0"
red = "0xdc7974"
white = "0xfeffff"
yellow = "0xece100"

[colors.primary]
foreground = "0xc5c8c6"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "terminal-font"
style = "Bold"

[font.bold_italic]
family = "terminal-font"
style = "Bold Italic"

[font.italic]
family = "terminal-font"
style = "Italic"

[font.normal]
family = "terminal-font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity = 0.9
dynamic_padding = true

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 0
y = 0
